### ISSUE TITLE
Would be great to have unit tests

### ISSUE THREAD

**Issue by samdark** [wapmorgan/yii2-inflection#1]
They're both a good helper and a proof the the library does its job correctly.

**Comment by wapmorgan** [comment]
@samdark How would be better to test it? Using Yii service locator or not?

**Comment by samdark** [comment]
I think testing w/o it is much better.

**Comment by wapmorgan** [comment]
This extension is so small that I test it with just two runs in cmd, changing app's language between runs.

**Comment by samdark** [comment]
Well, a unit tests will do that for you and show people that it runs fine right in the readme.

**Comment by wapmorgan** [comment]
Added tests for both languages.

**Comment by samdark** [comment]
Good.
