### ISSUE TITLE
Inflection returned NULL

### ISSUE THREAD

**Issue by ilya-shaydullin** [wapmorgan/yii2-inflection#3]
Inlection's methofd return NULL

```PHP
//common/config/main.php
'inflection' => [
            'class' => 'wapmorgan\yii2inflection\Inflection'
        ],
```

Method calling:
```PHP
echo Yii::$app->inflection->inflectName('Иванов Петр', Inflector::DATIVE);
```

**Comment by wapmorgan** [comment]
Did you set proper `language` of your application?

Like this **config/main.php**
```php
    'language' => 'ru_RU',
```
Because if applcation is configured to English language, this behavior is normal.

**Comment by wapmorgan** [comment]
[Updated extension](https://github.com/wapmorgan/yii2-inflection/releases/tag/1.0.2) so now it won't return `null` anymore.

**Comment by wapmorgan** [comment]
@ilusha2012 so, you still have this problem?

**Comment by ilya-shaydullin** [comment]
Yes, all work! Thank you! 
Can you add a prepositional case?

**Comment by wapmorgan** [comment]
Not sure if it's needed. Is there a real use case?

**Comment by wapmorgan** [comment]
@ilusha2012 Provide at least one use case for prepositional case, I think it's not necessary.

**Comment by ilya-shaydullin** [comment]
Sorry for the wait. Yes, it case necessary in my project. 
Example: "Москва" should be converting to "В Москве", "Обь" to "В оби". 
Thank you for your answer. I found another solution.

**Comment by wapmorgan** [comment]
You can use [Morphos](https://github.com/wapmorgan/Morphos) directly, it provides prepositional case (to get `оби`) and methods to add `в` preposition (`в Оби`, `во Владивостоке`).

**Comment by ilya-shaydullin** [comment]
Oh, ok. Thank you! I'll know.
