### ISSUE TITLE
Отсутствуют падежи.

### ISSUE THREAD

**Issue by ferrumfist** [wapmorgan/yii2-inflection#4]
Почему в реализации для Yii2 отсутствуют Винительный и Предложный падежи, хотя в исходной библиотеке wapmorgan/Morphos они реализованы и работают?

**Comment by wapmorgan** [comment]
@ferrumfist а в них есть необходимость? Я добавил базовые падежи, которые используются в большинстве языков.

**Comment by wapmorgan** [comment]
Исправлено в **1.0.3**.
